### ISSUE TITLE
selecting region issue and text box size is larger

### ISSUE THREAD

**Issue by fastthinker** [shashidhark/ASKResults#1]
1. I can see plain text box with region by default it shows 1. It doesn't looks like drop down.
2. After selecting a region it should display related colleges in next drop down, but that drop down box doesn't refreshes at all and it retains previous regions college code.
3. Scrollbar must be alligned to the right most side of the window.

**Comment by shashidhark** [comment]
Ok.. I got it.. Thank you for reporting issue..

**Comment by fastthinker** [comment]
Nice work. Keep up.
